import { motion } from 'motion/react';
import { Mail, Phone, Clock, Send, Plus, Minus, MessageSquare, ShieldCheck, Zap, Loader2, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';
import { cn } from '../lib/utils';
import { db } from '../lib/firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { contactAPI } from '../lib/api';

const faqs = [
  { 
    q: "Is OmniMind free to use?", 
    a: "Yes! OmniMind offers a free basic chat tier. For advanced features like multimodal analysis, document summarization, and image generation, we offer premium subscription plans." 
  },
  { 
    q: "How does the document summarizer work?", 
    a: "Our AI processes the text within your uploaded documents (PDF, DOCX, TXT) and uses neural semantic analysis to extract key entities, action items, and structural summaries." 
  },
  { 
    q: "Can I use OmniMind for commercial projects?", 
    a: "Absolutely. All outputs generated by OmniMind (text and images) are yours to use for commercial or personal purposes under our platform license." 
  },
  { 
    q: "Is my data secure?", 
    a: "User privacy is our top priority. All communications are encrypted, and your documents are processed in a secure environment. We do not sell your personal data." 
  }
];

export default function Contact() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [loading, setLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [formData, setFormData] = useState({ name: '', email: '', message: '' });

const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name || !formData.email || !formData.message) return;

    setLoading(true);
    try {
      // Submit to FastAPI backend (which saves to database and sends email to admin)
      await contactAPI.submit({
        name: formData.name,
        email: formData.email,
        message: formData.message
      });
      setSubmitted(true);
      setFormData({ name: '', email: '', message: '' });
      setTimeout(() => setSubmitted(false), 5000);
    } catch (err) {
      console.error("Submission failed:", err);
      // Fallback to Firebase if backend fails
      try {
        await addDoc(collection(db, 'contact_messages'), {
          ...formData,
          status: 'new',
          createdAt: serverTimestamp()
        });
        setSubmitted(true);
        setFormData({ name: '', email: '', message: '' });
        setTimeout(() => setSubmitted(false), 5000);
      } catch (fbErr) {
        console.error("Fallback failed:", fbErr);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="pb-24 pt-20 container mx-auto px-4 space-y-24">
      {/* Hero & Contact Info */}
      <section className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-start">
        <div className="space-y-10">
          <div className="space-y-4">
             <h1 className="text-4xl md:text-6xl font-display font-black leading-tight tracking-tight">Connect with <span className="text-primary italic">Intelligence</span></h1>
             <p className="text-gray-400 text-lg">Have a question or a vision for OmniMind? Our team operates 24/7 remotely to assist you immediately.</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
             <div className="p-8 rounded-3xl glass-card space-y-4 border-white/5">
                <Mail className="h-8 w-8 text-primary" />
                <h4 className="font-bold">Email Support</h4>
                <p className="text-sm text-gray-500">omnimind@gmail.com</p>
             </div>
             <div className="p-8 rounded-3xl glass-card space-y-4 border-white/5">
                <Phone className="h-8 w-8 text-primary" />
                <h4 className="font-bold">Phone Network</h4>
                <p className="text-sm text-gray-500">+91 9382731364</p>
             </div>
             <div className="p-8 rounded-3xl glass-card space-y-4 border-white/5">
                <Clock className="h-8 w-8 text-primary" />
                <h4 className="font-bold">Availability</h4>
                <p className="text-sm text-gray-500">24x7. Fully Remote.</p>
             </div>
             <div className="p-8 rounded-3xl glass-card bg-primary/10 space-y-4 border-primary/20">
                <Zap className="h-8 w-8 text-primary animate-pulse" />
                <h4 className="font-bold">Fast Response</h4>
                <p className="text-sm text-gray-500">Typical response <br/>Under 30 minutes.</p>
             </div>
          </div>
        </div>

        {/* Form */}
        <div className="glass-card p-8 md:p-12 relative overflow-hidden">
           <div className="absolute top-0 right-0 p-20 bg-primary/10 blur-[100px] rounded-full" />
           <form className="relative z-10 space-y-8" onSubmit={handleSubmit}>
              <h3 className="text-2xl font-bold flex items-center gap-3">
                {submitted ? <CheckCircle2 className="h-6 w-6 text-green-500" /> : <MessageSquare className="h-6 w-6 text-primary" />} 
                {submitted ? 'Transmission Successful' : 'Transmit a Message'}
              </h3>
              
              <div className="space-y-6">
                <div className="space-y-2">
                  <label className="text-xs font-bold uppercase tracking-widest text-gray-500 ml-1">Full Name</label>
                  <input 
                    required
                    value={formData.name}
                    onChange={(e) => setFormData({...formData, name: e.target.value})}
                    className="w-full bg-white/5 border border-white/10 rounded-xl py-4 px-6 focus:outline-none focus:border-primary transition-all" 
                    placeholder="Identify yourself..."
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-xs font-bold uppercase tracking-widest text-gray-500 ml-1">Email Connection</label>
                  <input 
                    required
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData({...formData, email: e.target.value})}
                    className="w-full bg-white/5 border border-white/10 rounded-xl py-4 px-6 focus:outline-none focus:border-primary transition-all" 
                    placeholder="Where can we reach you?"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-xs font-bold uppercase tracking-widest text-gray-500 ml-1">Your Message</label>
                  <textarea 
                    required
                    value={formData.message}
                    onChange={(e) => setFormData({...formData, message: e.target.value})}
                    className="w-full bg-white/5 border border-white/10 rounded-xl py-4 px-6 min-h-[150px] focus:outline-none focus:border-primary transition-all resize-none" 
                    placeholder="Describe your query in detail..."
                  />
                </div>
              </div>

              <button 
                type="submit"
                disabled={loading || submitted}
                className={cn(
                  "group w-full py-5 rounded-2xl font-black text-xl shadow-lg transition-all flex items-center justify-center gap-3",
                  submitted ? "bg-green-500 text-white shadow-green-500/20" : "bg-primary text-white shadow-primary/20 hover:scale-[1.02]"
                )}
              >
                 {loading ? <Loader2 className="h-6 w-6 animate-spin" /> : submitted ? 'Message Sent' : 'Send Pulse'} 
                 {!loading && !submitted && <Send className="h-5 w-5 transition-transform group-hover:translate-x-1" />}
              </button>
              <div className="flex justify-center gap-2 text-[10px] text-gray-600 uppercase tracking-widest font-bold">
                 <ShieldCheck className="h-3 w-3" /> Encrypted Transmission
              </div>
           </form>
        </div>
      </section>

      {/* FAQs */}
      <section className="space-y-12 max-w-4xl mx-auto">
        <div className="text-center space-y-4">
           <h2 className="text-3xl font-display font-bold">Intelligence <span className="text-primary italic">Protocol</span> (FAQ)</h2>
           <p className="text-gray-500">Common queries about our neural network platform.</p>
        </div>

        <div className="space-y-4">
           {faqs.map((faq, i) => (
             <div 
               key={i} 
               className={cn(
                 "rounded-2xl border transition-all overflow-hidden",
                 openFaq === i ? "bg-white/5 border-primary/30" : "bg-dark border-white/5"
               )}
             >
                <button 
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex items-center justify-between p-6 text-left"
                >
                   <span className="font-bold text-lg">{faq.q}</span>
                   {openFaq === i ? <Minus className="h-5 w-5 text-primary" /> : <Plus className="h-5 w-5 text-gray-500" />}
                </button>
                <motion.div 
                  initial={false}
                  animate={{ height: openFaq === i ? 'auto' : 0, opacity: openFaq === i ? 1 : 0 }}
                  className="overflow-hidden"
                >
                  <p className="px-6 pb-6 text-gray-500 leading-relaxed">{faq.a}</p>
                </motion.div>
             </div>
           ))}
        </div>
      </section>
    </div>
  );
}
